### PR TITLE
Chore/remove console logs

### PR DESCRIPTION
**Pull request by marika-jane**
- remove annoying console.logs
- run `npm audit fix`

### CODE REVIEW

**Comment by nobrayner** [comment]
HEEEEEEEEEEELLLLLLLLLLLLLLLLL yes!!!!!

**Review by emma-r-slight — APPROVED** [review]

**Comment by marika-jane** [comment]
I'm assuming `npm audit fix` won't break anything - is that right? I didn't add the --force flag

**Review by nobrayner — APPROVED** [review]

**Review by alexarcombe — APPROVED** [review]

**Comment by nobrayner** [comment]
Why are there two Netlify deploys? :sweat_smile:

**Comment by emma-r-slight** [comment]
> 

No idea!! A bug perhaps?

**Comment by marika-jane** [comment]
Just FYI there are still 19 'high severity vulnerabilities'

**Comment by emma-r-slight** [comment]
Ohhhh it might be because I think Kevin deployed this repo  to his personal Netlify "team" before he added it to the NC team.... therefore two deploys??

**Comment by nobrayner** [comment]
> Just FYI there are still 19 'high severity vulnerabilities'

That will be because it couldn't upgrade the deps within the version ranges specified. So either our dependecies need to update their deps, or we need to manually update ours :)

**Pull request merged**
